#!/bin/sh

green='\033[0;32m'
red='\033[0;31m'
nc='\033[0m'

# Check which files have been added
changed=`git diff --staged --name-only`
changed=`echo $changed | tr '\n' ' '`

cd ~/html/es/

fixed=0

for fn in $changed; do
    # If file exists and is in the app/ folder
    if [ -e "$fn" ] && [[ $fn == app/* ]]; then
        # Dry run to get status code
        ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer --quiet --dry-run fix $fn
        status=`echo $?`

        # Display status and re-add if fixed
        case $status in
            0) echo "  ${green}OK${nc}     $fn ";;
            8) echo "  ${red}fixed${nc}  $fn "
                ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer --quiet fix $fn
                git add $fn; ((fixed++));;
            *) echo "  ${red}UNKNOWN ERROR${nc}";;
        esac
    fi
done

# Change back to original directory
cd - > /dev/null

echo "";

